services:
  postgres:
    container_name: modern-stack-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - modernstack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ETL_USER: ${ETL_USER}
      ETL_PASS: ${ETL_PASS}
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 10

  pgadmin:
    container_name: modern-stack-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - ${PGA_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - modernstack
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  sqlserver:
    container_name: modern-stack-sqlserver
    build: ./sqlserver
    restart: unless-stopped
    ports:
      - ${SA_PORT}:1433
    networks:
      modernstack:
    volumes:
      - sqlserver:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_USER: ${SA_USER}
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
      ETL_USER: ${ETL_USER}
      ETL_PASS: ${ETL_PASS}
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "${SA_USER}",
          "-P",
          "${SA_PASSWORD}",
          "-Q",
          "SELECT 1",
          "-b",
          "-o",
          "/dev/null",
        ]
      start_period: 60s
      interval: 30s
      timeout: 10s
      retries: 10

  etl:
    build: ./etl
    restart: on-failure
    networks:
      modernstack:
    environment:
      ETL_USER: ${ETL_USER}
      ETL_PASS: ${ETL_PASS}
      PG_PORT: ${PG_PORT}
      SA_PORT: ${SA_PORT}
    depends_on:
      postgres:
        condition: service_healthy
      sqlserver:
        condition: service_healthy

networks:
  modernstack:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  sqlserver:
  etl:
