services:
  postgres:
    container_name: modern-stack-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    container_name: modern-stack-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
