services:
  postgres:
    container_name: modern-stack-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

    networks:
      - modernstack
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  pgadmin:
    container_name: modern-stack-pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - ${PGA_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - modernstack
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}

  sqlserver:
    container_name: modern-stack-sqlserver
    build: ./sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_USER: ${SA_USER}
      SA_PASSWORD: ${SA_PASSWORD}
      MSSQL_PID: ${MSSQL_PID}
    restart: unless-stopped
    ports:
      - ${SA_PORT}:1433
    networks:
      - modernstack
    volumes:
      - sqlserver:/var/opt/mssql

networks:
  modernstack:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  sqlserver:
