\set ETL_USER `echo $ETL_USER`
\set ETL_PASS `echo $ETL_PASS`

CREATE USER :ETL_USER WITH PASSWORD :'ETL_PASS';

CREATE DATABASE "AdventureWorks2022"
  WITH
  OWNER = :ETL_USER
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION_LIMIT = -1;

  CREATE DATABASE "AdventureWorksDW2022"
  WITH
  OWNER = :ETL_USER
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION_LIMIT = -1;

-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO :ETL_USER;

