CREATE DATABASE "AdventureWorks"
  WITH
  OWNER = postgres
  ENCODING = 'UTF8'
  LC_COLLATE = 'en_US.utf8'
  LC_CTYPE = 'en_US.utf8'
  TABLESPACE = pg_default
  CONNECTION_LIMIT = -1;

CREATE USER etl WITH PASSWORD 'demopass';
GRANT CONNECT ON DATABASE "AdventureWorks" TO etl;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO etl;

